# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7ddef76670cedc09b769a74ef093ae09547d854e82aae003b4abae9dd716a6dde7fc9e60ce16ba9c40e31b7538bc1fc7dcba01567806e629479183f3ab44ecd

test:
  secret_key_base: 16718af276a1188617587b0fc890dcc9343a3cc233bcda16b4fa72fd5e0048559b4ba313b2607bfcfdeecb34af458bc732a0b01e1e262839a56365b5f5262164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
